In [2]:
import pandas as pd
import numpy as np 
import os 

data_loc1 = '/tahoma/emsls60141/FT-ICR-MS/raw-data/2022_06/results_rerun/'
datafiles1 = os.listdir(data_loc1)
# Lets exclude everything except CSVs - note, we output the data in csv format. 
datafiles1 = [x for x in datafiles1 if '.csv' in x]
# In case we've made other files like Summary, Pivot, or Longform ALREADY, lets exclude them too...
datafiles1 = [x for x in datafiles1 if 'summary' not in x]
datafiles1 = [x for x in datafiles1 if 'Pivot' not in x]
datafiles1 = [x for x in datafiles1 if 'Longform' not in x]
datafiles1 = [x for x in datafiles1 if 'report' not in x]

In [3]:
num = [int(x[-8:-4]) for x in datafiles1]
datafiles1 = np.array(datafiles1)[np.argsort(num)]

In [4]:
df_longform = pd.DataFrame()
for datafile in datafiles1:
    df_tmp = pd.read_csv(data_loc1+'/'+datafile,index_col=0)
    df_tmp['Filename'] = datafile
    #If you have named your files well AND CONSISTENTLY, you can pull out the useful info from the filename
    #samplename = datafile.split('_')[3]
    #order = datafile.split('_')[4]
    #df_tmp['Sample'] = samplename
    #df_tmp['Order'] = order
    df_longform = df_longform.append(df_tmp)
    
# Export all the merged data to a single longform structure
df_longform.to_csv(data_loc1+'/'+'Longform_All.csv')#all peaks from all files in one file, adds filename column

#remove isotopic peaks and unassigned peaks
df_longform = df_longform[(df_longform['Is Isotopologue']==0)&
                          (df_longform['Heteroatom Class']!='unassigned')]
df_longform.to_csv(data_loc1+'/'+'Longform_Mono.csv')

/home/shic892/miniconda3/envs/jupyter_plot/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (17,20) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
data_loc2 = '/tahoma/emsls60141/FT-ICR-MS/raw-data/2022_11/results_rerun/'
datafiles2 = os.listdir(data_loc2)
# Lets exclude everything except CSVs - note, we output the data in csv format. 
datafiles2 = [x for x in datafiles2 if '.csv' in x]
# In case2 we've made other files like Summary, Pivot, or Longform ALREADY, lets exclude them too...
datafiles2 = [x for x in datafiles2 if 'summary' not in x]
datafiles2 = [x for x in datafiles2 if 'Pivot' not in x]
datafiles2 = [x for x in datafiles2 if 'Longform' not in x]
datafiles2 = [x for x in datafiles2 if 'report' not in x]

In [6]:
num = [int(x[-8:-4]) for x in datafiles2]
datafiles2 = np.array(datafiles2)[np.argsort(num)]

In [7]:
df_longform = pd.DataFrame()
for datafile in datafiles2:
    df_tmp = pd.read_csv(data_loc2+'/'+datafile,index_col=0)
    df_tmp['Filename'] = datafile
    #If you have named your files well AND CONSISTENTLY, you can pull out the useful info from the filename
    #samplename = datafile.split('_')[3]
    #order = datafile.split('_')[4]
    #df_tmp['Sample'] = samplename
    #df_tmp['Order'] = order
    df_longform = df_longform.append(df_tmp)
    
# Export all the merged data to a single longform structure
df_longform.to_csv(data_loc2+'/'+'Longform_All.csv')#all peaks from all files in one file, adds filename column

#remove isotopic peaks and unassigned peaks
df_longform = df_longform[(df_longform['Is Isotopologue']==0)&
                          (df_longform['Heteroatom Class']!='unassigned')]
df_longform.to_csv(data_loc2+'/'+'Longform_Mono.csv')

In [8]:
import pandas as pd
data_loc1 = '/tahoma/emsls60141/FT-ICR-MS/raw-data/2022_06/results_rerun/'
data_loc2 = '/tahoma/emsls60141/FT-ICR-MS/raw-data/2022_11/results_rerun/'
df_longForm_06 = pd.read_csv(data_loc1+'Longform_Mono.csv')
df_longForm_06 = df_longForm_06.loc[(df_longForm_06['Confidence Score']>0.5) & (df_longForm_06['m/z']>200) & (df_longForm_06['m/z']<1000)]
df_longForm_11 = pd.read_csv(data_loc2+'Longform_Mono.csv')
df_longForm_11 = df_longForm_11.loc[(df_longForm_11['Confidence Score']>0.5) & (df_longForm_11['m/z']>200) & (df_longForm_11['m/z']<1000)]

In [9]:
df_pivot_06 = df_longForm_06.pivot_table(index='Molecular Formula',columns='Filename',values='Peak Height')
df_pivot_11 = df_longForm_11.pivot_table(index='Molecular Formula',columns='Filename',values='Peak Height')

In [10]:
df_uniqueForm_06 = df_longForm_06.drop_duplicates(['Molecular Formula'])
colstokeep = ['C', 'H', 'O', 'S', 'N','P', 'Molecular Formula', 'Index',
              'Calculated m/z', 'DBE','H/C', 'O/C', 'Heteroatom Class']
df_uniqueForm_06 = df_uniqueForm_06[colstokeep]
df_uniqueForm_06 = df_uniqueForm_06.reset_index()
df_uniqueForm_06 = df_uniqueForm_06.set_index('Molecular Formula')

In [11]:
df_uniqueForm_11 = df_longForm_11.drop_duplicates(['Molecular Formula'])
df_uniqueForm_11 = df_uniqueForm_11[colstokeep]
df_uniqueForm_11 = df_uniqueForm_11.reset_index()
df_uniqueForm_11 = df_uniqueForm_11.set_index('Molecular Formula')

In [12]:
df_uniqueForm_06.append(df_uniqueForm_11)

,index,C,H,O,S,N,P,Index,Calculated m/z,DBE,H/C,O/C,Heteroatom Class
Molecular Formula,,,,,,,,,,,,,
C6 H7 O2 N2 P1 S1,39,6.0,7.0,2.0,1.0,2.0,1.0,77,200.989309,5.0,1.166667,0.333333,N2 S1 P1 O2
C10 H18 O4,40,10.0,18.0,4.0,NaN,NaN,NaN,78,201.113233,2.0,1.800000,0.400000,O4
C10 H20 O4,41,10.0,20.0,4.0,NaN,NaN,NaN,80,203.128883,1.0,2.000000,0.400000,O4
C14 H22 O1,42,14.0,22.0,1.0,NaN,NaN,NaN,81,205.159789,4.0,1.571429,0.071429,O1
C10 H8 O3 S1,43,10.0,8.0,3.0,1.0,NaN,NaN,83,207.012139,7.0,0.800000,0.300000,S1 O3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
C47 H46 O3 N3 P1 S2,3166286,47.0,46.0,3.0,2.0,3.0,1.0,10031,794.264545,27.0,0.978723,0.063830,N3 S2 P1 O3
C58 H54 O3 N1 P1 S2,3166342,58.0,54.0,3.0,2.0,1.0,1.0,10066,906.320997,33.0,0.931034,0.051724,N1 S2 P1 O3
C24 H37 O5 N1 S1,3166366,24.0,37.0,5.0,1.0,1.0,NaN,79,450.231968,7.0,1.541667,0.208333,N1 S1 O5
C51 H53 O1 P1 S1,3166371,51.0,53.0,1.0,1.0,NaN,1.0,86,743.348198,26.0,1.039216,0.019608,S1 P1 O1
C47 H41 O19 N3 S1,3166372,47.0,41.0,19.0,1.0,3.0,NaN,88,982.198221,29.0,0.872340,0.404255,N3 S1 O19

In [13]:
pd.concat([df_uniqueForm_06, df_uniqueForm_11], axis=0).drop_duplicates('Calculated m/z')

,index,C,H,O,S,N,P,Index,Calculated m/z,DBE,H/C,O/C,Heteroatom Class
Molecular Formula,,,,,,,,,,,,,
C6 H7 O2 N2 P1 S1,39,6.0,7.0,2.0,1.0,2.0,1.0,77,200.989309,5.0,1.166667,0.333333,N2 S1 P1 O2
C10 H18 O4,40,10.0,18.0,4.0,NaN,NaN,NaN,78,201.113233,2.0,1.800000,0.400000,O4
C10 H20 O4,41,10.0,20.0,4.0,NaN,NaN,NaN,80,203.128883,1.0,2.000000,0.400000,O4
C14 H22 O1,42,14.0,22.0,1.0,NaN,NaN,NaN,81,205.159789,4.0,1.571429,0.071429,O1
C10 H8 O3 S1,43,10.0,8.0,3.0,1.0,NaN,NaN,83,207.012139,7.0,0.800000,0.300000,S1 O3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
C47 H46 O3 N3 P1 S2,3166286,47.0,46.0,3.0,2.0,3.0,1.0,10031,794.264545,27.0,0.978723,0.063830,N3 S2 P1 O3
C58 H54 O3 N1 P1 S2,3166342,58.0,54.0,3.0,2.0,1.0,1.0,10066,906.320997,33.0,0.931034,0.051724,N1 S2 P1 O3
C24 H37 O5 N1 S1,3166366,24.0,37.0,5.0,1.0,1.0,NaN,79,450.231968,7.0,1.541667,0.208333,N1 S1 O5
C51 H53 O1 P1 S1,3166371,51.0,53.0,1.0,1.0,NaN,1.0,86,743.348198,26.0,1.039216,0.019608,S1 P1 O1
C47 H41 O19 N3 S1,3166372,47.0,41.0,19.0,1.0,3.0,NaN,88,982.198221,29.0,0.872340,0.404255,N3 S1 O19

In [14]:
df_pivot_uniq = pd.concat([df_uniqueForm_06, df_uniqueForm_11], axis=0).drop_duplicates('Calculated m/z')
df_pivot_uniq.to_csv('1000s_corems2_FTICR_peak_def_rerun.csv')

In [15]:
df_pivot_uniq

,index,C,H,O,S,N,P,Index,Calculated m/z,DBE,H/C,O/C,Heteroatom Class
Molecular Formula,,,,,,,,,,,,,
C6 H7 O2 N2 P1 S1,39,6.0,7.0,2.0,1.0,2.0,1.0,77,200.989309,5.0,1.166667,0.333333,N2 S1 P1 O2
C10 H18 O4,40,10.0,18.0,4.0,NaN,NaN,NaN,78,201.113233,2.0,1.800000,0.400000,O4
C10 H20 O4,41,10.0,20.0,4.0,NaN,NaN,NaN,80,203.128883,1.0,2.000000,0.400000,O4
C14 H22 O1,42,14.0,22.0,1.0,NaN,NaN,NaN,81,205.159789,4.0,1.571429,0.071429,O1
C10 H8 O3 S1,43,10.0,8.0,3.0,1.0,NaN,NaN,83,207.012139,7.0,0.800000,0.300000,S1 O3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
C47 H46 O3 N3 P1 S2,3166286,47.0,46.0,3.0,2.0,3.0,1.0,10031,794.264545,27.0,0.978723,0.063830,N3 S2 P1 O3
C58 H54 O3 N1 P1 S2,3166342,58.0,54.0,3.0,2.0,1.0,1.0,10066,906.320997,33.0,0.931034,0.051724,N1 S2 P1 O3
C24 H37 O5 N1 S1,3166366,24.0,37.0,5.0,1.0,1.0,NaN,79,450.231968,7.0,1.541667,0.208333,N1 S1 O5
C51 H53 O1 P1 S1,3166371,51.0,53.0,1.0,1.0,NaN,1.0,86,743.348198,26.0,1.039216,0.019608,S1 P1 O1
C47 H41 O19 N3 S1,3166372,47.0,41.0,19.0,1.0,3.0,NaN,88,982.198221,29.0,0.872340,0.404255,N3 S1 O19

In [13]:
import numpy as np
names = df_pivot_06.columns.values
names = [x for x in names if 'run1' not in x]
num = [int(x[-8:-4]) for x in names]
names = np.array(names)[np.where([(i<=3619 or i>=3628) for i in num])]
df_pivot_06 = df_pivot_06.loc[:,names]

In [16]:
print(df_pivot_06.shape)
print(df_pivot_11.shape)

# remove all the features that present more than twice in any blanks (lab blank, and spe blank)
df_pivot_06 = df_pivot_06.loc[(df_pivot_06.loc[:,df_pivot_06.columns.str.contains('MeOH')].isna()==False).sum(axis=1)<=2,:]
df_pivot_06 = df_pivot_06.loc[(df_pivot_06.loc[:,df_pivot_06.columns.str.contains('Gilson')].isna()==False).sum(axis=1)<=2,:]
df_pivot_11 = df_pivot_11.loc[(df_pivot_11.loc[:,df_pivot_11.columns.str.contains('BLNK')].isna()==False).sum(axis=1)<=2,:]
df_pivot_11 = df_pivot_11.loc[(df_pivot_11.loc[:,df_pivot_11.columns.str.contains('Blank')].isna()==False).sum(axis=1)<=2,:]
print(df_pivot_06.shape)
print(df_pivot_11.shape)

(77830, 276)
(145471, 314)
(74927, 276)
(142914, 314)

In [17]:
df_pivot_06_qc = df_pivot_06.loc[:,df_pivot_06.columns.str.contains('SRFA|run1|MeOH|Gilson')==False]
df_pivot_11_qc = df_pivot_11.loc[:,df_pivot_11.columns.str.contains('SRFA|p01|Blank|BLNK')==False]

print(df_pivot_06_qc.shape)
print(df_pivot_11_qc.shape)

(74927, 127)
(142914, 259)

In [18]:
np.savetxt('corems2_FTICR_2206_rerun.csv', np.array(df_pivot_06_qc.columns.values),fmt='%s', delimiter=',')
np.savetxt('corems2_FTICR_2211_rerun.csv', np.array(df_pivot_11_qc.columns.values),fmt='%s', delimiter=',')

In [19]:
df_pivot_all = pd.concat([df_pivot_06_qc, df_pivot_11_qc], axis=1)
print(df_pivot_all.columns)

Index(['corems2_1000S_CFS1_FTMS_SPE_BTM_1_run2_Fir_22Apr22_300SA_p01_99_1_3456.csv',
       'corems2_1000S_CFS1_FTMS_SPE_BTM_2_run2_Fir_22Apr22_300SA_p01_143_1_3500.csv',
       'corems2_1000S_CFS1_FTMS_SPE_BTM_3_run2_Fir_26Apr22_300SA_p01_6_1_3597.csv',
       'corems2_1000S_CFS1_FTMS_SPE_TOP_1_run2_Fir_22Apr22_300SA_p01_144_1_3501.csv',
       'corems2_1000S_CFS1_FTMS_SPE_TOP_2_run2_Fir_22Apr22_300SA_p01_104_1_3461.csv',
       'corems2_1000S_CFS1_FTMS_SPE_TOP_3_run2_Fir_27Apr22_300SA_p01_1_1_3613.csv',
       'corems2_1000S_CFS2_FTMS_SPE_BTM_1_run2_Fir_22Apr22_300SA_p01_107_1_3464.csv',
       'corems2_1000S_CFS2_FTMS_SPE_BTM_2_run2_Fir_22Apr22_300SA_p01_133_1_3490.csv',
       'corems2_1000S_CFS2_FTMS_SPE_BTM_3_run2_Fir_22Apr22_300SA_p01_96_1_3453.csv',
       'corems2_1000S_CFS2_FTMS_SPE_TOP_1_run2_Fir_22Apr22_300SA_p01_98_1_3455.csv',
       ...
       'corems2_1000s_WY10_FTMS_SPE_BTM_3_02Nov22_Mag_300SA_p025_132_1_7247.csv',
       'corems2_1000s_WY10_FTMS_SPE_TOP_1_02Nov22_Mag_300SA_p025_138_1_7253.csv',
       'corems2_1000s_WY10_FTMS_SPE_TOP_2_31Oct22_Mag_300SA_p025_179_1_7192.csv',
       'corems2_1000s_WY10_FTMS_SPE_TOP_3_31Oct22_Mag_300SA_p025_159_1_7172.csv',
       'corems2_1000s_WY15_FTMS_SPE_BTM_1_01Nov22_Mag_300SA_p025_212_1_7225.csv',
       'corems2_1000s_WY15_FTMS_SPE_BTM_2_31Oct22_Mag_300SA_p025_150_1_7163.csv',
       'corems2_1000s_WY15_FTMS_SPE_BTM_3_01Nov22_Mag_300SA_p025_204_1_7217.csv',
       'corems2_1000s_WY15_FTMS_SPE_TOP_1_02Nov22_Mag_300SA_p025_133_1_7248.csv',
       'corems2_1000s_WY15_FTMS_SPE_TOP_2_01Nov22_Mag_300SA_p025_198_1_7211.csv',
       'corems2_1000s_WY15_FTMS_SPE_TOP_3_25Oct22_Mag_300SA_p025_106_1_7019.csv'],
      dtype='object', name='Filename', length=386)

In [20]:
df_pivot_all.columns = df_pivot_all.columns.str.replace('_RR_', '_')
site_names = [x[14:19]+x[28:31] for x in list(df_pivot_all)]
site_names

['CFS1_BTM',
 'CFS1_BTM',
 'CFS1_BTM',
 'CFS1_TOP',
 'CFS1_TOP',
 'CFS1_TOP',
 'CFS2_BTM',
 'CFS2_BTM',
 'CFS2_BTM',
 'CFS2_TOP',
 'CFS2_TOP',
 'CFS2_TOP',
 'FTA3_BTM',
 'FTA3_BTM',
 'FTA3_BTM',
 'FTA3_BTM',
 'FTA3_TOP',
 'FTA3_TOP',
 'FTA3_TOP',
 'FTA5_BTM',
 'FTA5_BTM',
 'FTA5_BTM',
 'FTA5_TOP',
 'FTA5_TOP',
 'FTA5_TOP',
 'NWBA_BTM',
 'NWBA_BTM',
 'NWBA_BTM',
 'NWBA_TOP',
 'NWBA_TOP',
 'NWBA_TOP',
 'NWBB_BTM',
 'NWBB_BTM',
 'NWBB_BTM',
 'NWBB_TOP',
 'NWBB_TOP',
 'NWBB_TOP',
 'NWBC_BTM',
 'NWBC_BTM',
 'NWBC_BTM',
 'NWBC_TOP',
 'NWBC_TOP',
 'NWBC_TOP',
 'OCTB_BTM',
 'OCTB_BTM',
 'OCTB_BTM',
 'OCTB_TOP',
 'OCTB_TOP',
 'OCTB_TOP',
 'OCTU_BTM',
 'OCTU_BTM',
 'OCTU_BTM',
 'OCTU_TOP',
 'OCTU_TOP',
 'OCTU_TOP',
 'OKPF_BTM',
 'OKPF_BTM',
 'OKPF_BTM',
 'OKPF_TOP',
 'OKPF_TOP',
 'OKPF_TOP',
 'PETF_BTM',
 'PETF_BTM',
 'PETF_BTM',
 'PETF_TOP',
 'PETF_TOP',
 'PETF_TOP',
 'PHTU_BTM',
 'PHTU_BTM',
 'PHTU_BTM',
 'PHTU_TOP',
 'PHTU_TOP',
 'PHTU_TOP',
 'PPRH_BTM',
 'PPRH_BTM',
 'PPRH_BTM',
 'PPRH_TOP',
 'PPRH_TOP',
 'PPRH_TOP',
 'PRS1_BTM',
 'PRS1_BTM',
 'PRS1_BTM',
 'PRS1_TOP',
 'PRS1_TOP',
 'PRS1_TOP',
 'PRS2_BTM',
 'PRS2_BTM',
 'PRS2_BTM',
 'PRS2_TOP',
 'PRS2_TOP',
 'PRS2_TOP',
 'WLLO_BTM',
 'WLLO_BTM',
 'WLLO_BTM',
 'WLLO_TOP',
 'WLLO_TOP',
 'WLLO_TOP',
 'WLUP_BTM',
 'WLUP_BTM',
 'WLUP_BTM',
 'WLUP_BTM',
 'WLUP_TOP',
 'WLUP_TOP',
 'WLUP_TOP',
 'WSU1_BTM',
 'WSU1_BTM',
 'WSU1_BTM',
 'WSU1_BTM',
 'WSU1_TOP',
 'WSU1_TOP',
 'WSU1_TOP',
 'WSU2_BTM',
 'WSU2_BTM',
 'WSU2_BTM',
 'WSU2_BTM',
 'WSU2_BTM',
 'WSU2_BTM',
 'WSU2_TOP',
 'WSU2_TOP',
 'WSU2_TOP',
 'WSU3_BTM',
 'WSU3_BTM',
 'WSU3_BTM',
 'WSU3_TOP',
 'WSU3_TOP',
 'WSU3_TOP',
 'WSU3_TOP',
 'ANZA_BTM',
 'ANZA_BTM',
 'ANZA_BTM',
 'ANZA_TOP',
 'ANZA_TOP',
 'ANZA_TOP',
 'BLAN_BTM',
 'BLAN_BTM',
 'BLAN_BTM',
 'BLAN_TOP',
 'BLAN_TOP',
 'BLAN_TOP',
 'CLBJ_BTM',
 'CLBJ_BTM',
 'CLBJ_BTM',
 'CLBJ_TOP',
 'CLBJ_TOP',
 'CLBJ_TOP',
 'CPER_TOP',
 'CPER_TOP',
 'CPER_TOP',
 'DCFS_BTM',
 'DCFS_BTM',
 'DCFS_BTM',
 'DCFS_TOP',
 'DCFS_TOP',
 'DCFS_TOP',
 'DELA_BTM',
 'DELA_BTM',
 'DELA_BTM',
 'DELA_TOP',
 'DELA_TOP',
 'DELA_TOP',
 'DSNY_BTM',
 'DSNY_BTM',
 'DSNY_BTM',
 'DSNY_TOP',
 'DSNY_TOP',
 'DSNY_TOP',
 'GRSM_BTM',
 'GRSM_BTM',
 'GRSM_BTM',
 'GRSM_TOP',
 'GRSM_TOP',
 'GRSM_TOP',
 'ISCC_BTM',
 'ISCC_BTM',
 'ISCC_BTM',
 'ISCC_TOP',
 'ISCC_TOP',
 'ISCC_TOP',
 'ISNC_BTM',
 'ISNC_BTM',
 'ISNC_BTM',
 'ISNC_TOP',
 'ISNC_TOP',
 'ISNC_TOP',
 'JERC_BTM',
 'JERC_BTM',
 'JERC_BTM',
 'JERC_TOP',
 'JERC_TOP',
 'JERC_TOP',
 'JORN_BTM',
 'JORN_BTM',
 'JORN_BTM',
 'JORN_TOP',
 'JORN_TOP',
 'JORN_TOP',
 'KONA_BTM',
 'KONA_BTM',
 'KONA_BTM',
 'KONA_TOP',
 'KONA_TOP',
 'KONA_TOP',
 'KONZ_BTM',
 'KONZ_BTM',
 'KONZ_BTM',
 'KONZ_TOP',
 'KONZ_TOP',
 'KONZ_TOP',
 'LENO_BTM',
 'LENO_BTM',
 'LENO_BTM',
 'LENO_TOP',
 'LENO_TOP',
 'LENO_TOP',
 'MLBS_BTM',
 'MLBS_BTM',
 'MLBS_BTM',
 'MLBS_TOP',
 'MLBS_TOP',
 'MLBS_TOP',
 'MOAB_BTM',
 'MOAB_BTM',
 'MOAB_TOP',
 'MOAB_TOP',
 'MOAB_TOP',
 'NOGP_BTM',
 'NOGP_BTM',
 'NOGP_BTM',
 'NOGP_TOP',
 'NOGP_TOP',
 'NOGP_TOP',
 'OAES_BTM',
 'OAES_BTM',
 'OAES_BTM',
 'OAES_TOP',
 'OAES_TOP',
 'OAES_TOP',
 'OKPF_BTM',
 'OKPF_BTM',
 'OKPF_BTM',
 'OKPF_TOP',
 'OKPF_TOP',
 'OKPF_TOP',
 'ONAQ_BTM',
 'ONAQ_BTM',
 'ONAQ_BTM',
 'ONAQ_TOP',
 'ONAQ_TOP',
 'ONAQ_TOP',
 'ORNL_BTM',
 'ORNL_BTM',
 'ORNL_BTM',
 'ORNL_TOP',
 'ORNL_TOP',
 'ORNL_TOP',
 'OSBS_BTM',
 'OSBS_BTM',
 'OSBS_BTM',
 'OSBS_TOP',
 'OSBS_TOP',
 'OSBS_TOP',
 'RMNP_BTM',
 'RMNP_BTM',
 'RMNP_BTM',
 'RMNP_TOP',
 'RMNP_TOP',
 'RMNP_TOP',
 'SCBI_BTM',
 'SCBI_BTM',
 'SCBI_BTM',
 'SCBI_TOP',
 'SCBI_TOP',
 'SCBI_TOP',
 'SERC_BTM',
 'SERC_BTM',
 'SERC_BTM',
 'SERC_TOP',
 'SERC_TOP',
 'SERC_TOP',
 'SJER_BTM',
 'SJER_BTM',
 'SJER_BTM',
 'SJER_TOP',
 'SJER_TOP',
 'SJER_TOP',
 'SOAP_BTM',
 'SOAP_BTM',
 'SOAP_BTM',
 'SOAP_TOP',
 'SOAP_TOP',
 'SOAP_TOP',
 'SRER_BTM',
 'SRER_BTM',
 'SRER_BTM',
 'SRER_TOP',
 'SRER_TOP',
 'SRER_TOP',
 'SRR1_BTM',
 'SRR1_BTM',
 'SRR1_BTM',
 'SRR1_TOP',
 'SRR1_TOP',
 'SRR1_TOP',
 'STER_TOP',
 'STER_TOP',
 'STER_TOP',
 'TALL_BTM',
 'TALL_BTM',
 'TALL_BTM',
 'TALL_TOP',
 'TALL_TOP',
 'TALL_TOP',
 'TEAK_BTM',
 'TEAK_BTM',
 'TEAK_BTM',
 'TEAK_TOP',
 'TEAK_TOP',
 'TEAK_TOP',
 'UKFS_BTM',
 'UKFS_BTM',
 'UKFS_BTM',
 'UKFS_BTM',
 'UKFS_TOP',
 'UKFS_TOP',
 'UKFS_TOP',
 'UKFS_TOP',
 'UT12_BTM',
 'UT12_BTM',
 'UT12_BTM',
 'UT12_TOP',
 'UT12_TOP',
 'UT12_TOP',
 'UT19_BTM',
 'UT19_BTM',
 'UT19_BTM',
 'UT19_TOP',
 'UT19_TOP',
 'UT19_TOP',
 'UT23_BTM',
 'UT23_BTM',
 'UT23_BTM',
 'UT23_TOP',
 'UT23_TOP',
 'UT23_TOP',
 'UT24_BTM',
 'UT24_BTM',
 'UT24_BTM',
 'UT24_TOP',
 'UT24_TOP',
 'UT24_TOP',
 'UT32_BTM',
 'UT32_BTM',
 'UT32_BTM',
 'UT32_TOP',
 'UT32_TOP',
 'UT32_TOP',
 'WY01_BTM',
 'WY01_BTM',
 'WY01_BTM',
 'WY01_TOP',
 'WY01_TOP',
 'WY01_TOP',
 'WY03_BTM',
 'WY03_BTM',
 'WY03_BTM',
 'WY03_TOP',
 'WY03_TOP',
 'WY03_TOP',
 'WY09_BTM',
 'WY09_BTM',
 'WY09_BTM',
 'WY09_TOP',
 'WY09_TOP',
 'WY09_TOP',
 'WY10_BTM',
 'WY10_BTM',
 'WY10_BTM',
 'WY10_TOP',
 'WY10_TOP',
 'WY10_TOP',
 'WY15_BTM',
 'WY15_BTM',
 'WY15_BTM',
 'WY15_TOP',
 'WY15_TOP',
 'WY15_TOP']

In [21]:
df_sites_qc = df_pivot_all.T
df_sites_qc['short'] = site_names
df_sites_qc = df_sites_qc.replace(np.nan, 0)
df_sites_qc_trip = df_sites_qc.groupby(['short']).median()
df_sites_qc_trip

Molecular Formula,C10 H10 O10,C10 H10 O3 N2,C10 H10 O4 N2,C10 H10 O4 N2 S1,C10 H10 O4 S1,C10 H10 O5 N2,C10 H10 O5 N2 S1,C10 H10 O5 S1,C10 H10 O6 N1 P1,C10 H10 O6 N2,...,C9 H9 O7 N3,C9 H9 O7 N3 S1,C9 H9 O8 N1 S1,C9 H9 O8 N2 P1,C9 H9 O8 N3,C9 H9 O8 P1,C9 H9 O9 N1,C9 H9 O9 N1 S1,C9 H9 O9 N3,C9 H9 O9 P1
short,,,,,,,,,,,,,,,,,,,,,
ANZA_BTM,0.000000e+00,0.000000e+00,2.572197e+06,0.0,0.000000e+00,3.623174e+06,0.000000e+00,0.000000e+00,0.0,2.528737e+06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ANZA_TOP,0.000000e+00,3.338778e+06,6.903938e+06,0.0,0.000000e+00,1.068255e+07,0.000000e+00,3.112529e+06,0.0,1.077506e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BLAN_BTM,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BLAN_TOP,0.000000e+00,2.864293e+06,5.269300e+06,0.0,0.000000e+00,1.108679e+07,3.110294e+06,3.671582e+06,0.0,1.388098e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CFS1_BTM,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WY09_TOP,8.135066e+06,3.019463e+06,6.648593e+06,0.0,3.236519e+06,1.496666e+07,3.881480e+06,7.358745e+06,0.0,1.301807e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WY10_BTM,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,1.586922e+07,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WY10_TOP,2.485326e+06,0.000000e+00,7.035950e+06,0.0,0.000000e+00,1.259030e+07,0.000000e+00,5.052686e+06,0.0,1.238345e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WY15_BTM,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WY15_TOP,7.424763e+06,0.000000e+00,0.000000e+00,0.0,0.000000e+00,9.669864e+06,0.000000e+00,6.033841e+06,0.0,1.018943e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
df_sites_qc_trip_01 = df_sites_qc_trip.loc[:,df_sites_qc_trip.sum()>0]
df_sites_qc_trip_01[df_sites_qc_trip_01>0] = 1
df_sites_qc_trip_01

/home/shic892/miniconda3/envs/jupyter_plot/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/shic892/miniconda3/envs/jupyter_plot/lib/python3.7/site-packages/pandas/core/frame.py:3718: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._where(-key, value, inplace=True)

Molecular Formula,C10 H10 O10,C10 H10 O3 N2,C10 H10 O4 N2,C10 H10 O4 N2 S1,C10 H10 O4 S1,C10 H10 O5 N2,C10 H10 O5 N2 S1,C10 H10 O5 S1,C10 H10 O6 N2,C10 H10 O6 N2 S1,...,C9 H9 O10 P1,C9 H9 O4 N1 S2,C9 H9 O6 N3 S1,C9 H9 O6 P1,C9 H9 O7 N3,C9 H9 O8 N1 S1,C9 H9 O8 N3,C9 H9 O9 N1,C9 H9 O9 N1 S1,C9 H9 O9 N3
short,,,,,,,,,,,,,,,,,,,,,
ANZA_BTM,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ANZA_TOP,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BLAN_BTM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BLAN_TOP,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CFS1_BTM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WY09_TOP,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
WY10_BTM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WY10_TOP,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WY15_BTM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WY15_TOP,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
df_sites_qc_trip_01.to_csv('1000_soils_124x66727_061224.csv')

In [30]:
df_sites_qc_trip_01.columns = df_pivot_uniq.loc[df_sites_qc_trip_01.columns.values,'Calculated m/z'].values

In [32]:
df_sites_qc_trip_01.T.to_csv('1000_soils_124x66727_061224_mz.csv')

In [102]:
print(df_sites_qc_trip_01.sum(axis=1).values)

[ 2956. 10047.   466. 17462.  4280.  3226.  2329.   941.  8154. 17163.
 15938.  2847. 16425.   637.  3747.  1766.  9231.  3459.  6200.  5061.
 10613.  7302.  6260. 15104. 18990. 10458.  7661.  2676.  6118.  3209.
  3234.  1195.  3712.  3116.  5798.  3335.  4723. 11531.  3716.  1081.
  1430.  2322. 19069.  5260.  4150.  3886.  5765.  9698.  7413.   777.
  2082.  2365.  6782.  6527.  5681.  8651. 13004.   367.  2098.  2149.
  7143.  4689.  7005.  3989.  5518.  5943.  3155.   955.  1169. 10933.
  3268.  2479.  6154. 11653. 18129.  1483.  6787. 13012. 14002. 14592.
 26960.  3196.  9026.  7475.  8378.  2801.  6124.  1924.  3270.  3240.
  1565. 13323. 15771.  8232. 14304. 10778.  4236.  5050.  8943. 18417.
  4500. 18416.  3925.  6152.  9496.  3439.  9505.  2864.  3874.  4186.
  8627.  9514.  1830.  6235.  6834. 21597.  6076. 20487. 11302. 24422.
  3006. 13196.  4293. 11538.]

In [97]:
df_sites_qc = df_sites_qc.iloc[:,:df_sites_qc.shape[1]-1]
df_sites_qc.loc[:,df_sites_qc.sum()>0]

Molecular Formula,C10 H10 O10,C10 H10 O3 N2,C10 H10 O4 N2,C10 H10 O4 S1,C10 H10 O4 S1 N2,C10 H10 O5 N2,C10 H10 O5 S1,C10 H10 O5 S1 N2,C10 H10 O6 N1 P1,C10 H10 O6 N2,...,C9 H9 O6 S1 N3,C9 H9 O7 N3,C9 H9 O7 S1 N3,C9 H9 O8 N3,C9 H9 O8 P1,C9 H9 O8 S1 N1,C9 H9 O9 N1,C9 H9 O9 N3,C9 H9 O9 P1,C9 H9 O9 S1 N1
Filename,,,,,,,,,,,,,,,,,,,,,
corems2_1000S_CFS1_FTMS_SPE_BTM_1_run2_Fir_22Apr22_300SA_p01_99_1_3456.csv,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000S_CFS1_FTMS_SPE_BTM_2_run2_Fir_22Apr22_300SA_p01_143_1_3500.csv,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000S_CFS1_FTMS_SPE_BTM_3_run2_Fir_26Apr22_300SA_p01_6_1_3597.csv,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,2.966689e+06,3.036363e+06,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000S_CFS1_FTMS_SPE_TOP_1_run2_Fir_22Apr22_300SA_p01_144_1_3501.csv,0.000000e+00,8.610426e+06,1.449407e+07,0.000000e+00,0.0,1.802095e+07,0.000000e+00,0.0,0.0,1.691103e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000S_CFS1_FTMS_SPE_TOP_2_run2_Fir_22Apr22_300SA_p01_104_1_3461.csv,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.654479e+07,0.000000e+00,0.0,0.0,1.939689e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
corems2_1000s_WY15_FTMS_SPE_BTM_2_31Oct22_Mag_300SA_p025_150_1_7163.csv,3.091252e+06,0.000000e+00,2.171901e+06,0.000000e+00,0.0,3.727726e+06,4.046262e+06,0.0,0.0,2.942966e+06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000s_WY15_FTMS_SPE_BTM_3_01Nov22_Mag_300SA_p025_204_1_7217.csv,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000s_WY15_FTMS_SPE_TOP_1_02Nov22_Mag_300SA_p025_133_1_7248.csv,1.009589e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.0,9.669864e+06,6.033841e+06,0.0,0.0,1.018943e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000s_WY15_FTMS_SPE_TOP_2_01Nov22_Mag_300SA_p025_198_1_7211.csv,7.424763e+06,2.946583e+06,4.961554e+06,2.963579e+06,0.0,1.007721e+07,7.402560e+06,0.0,0.0,1.076168e+07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
corems2_1000s_WY15_FTMS_SPE_TOP_3_25Oct22_Mag_300SA_p025_106_1_7019.csv,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,7.440307e+06,0.000000e+00,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [98]:
df_sites_qc.to_csv('corems2_1000_soils_202206_202211_qc_allsample_022124.csv')

In [1]:
import pandas as pd
import numpy as np

df_sites_qc = pd.read_csv('/home/shic892/corems/1000_soils_124x61959_022124.csv', index_col=0)
site_depth = [x[5:8] for x in df_sites_qc.index.values]
df_sites_qc_top = df_sites_qc.iloc[[x=='TOP' for x in site_depth],:]
df_sites_qc_top = df_sites_qc_top.loc[:,df_sites_qc_top.sum()>0]
df_sites_qc_btm = df_sites_qc.iloc[[x=='BTM' for x in site_depth],:]
df_sites_qc_btm = df_sites_qc_btm.loc[:,df_sites_qc_btm.sum()>0]

In [7]:
df_sites_qc_top.T.to_csv('1000_soils_top_56575x63_022124.csv')

In [5]:
df_sites_qc_btm.T.to_csv('1000_soils_btm_37242x61_022124.csv')

In [2]:
df_pivot_def = pd.read_csv('1000s_corems2_FTICR_peak_def.csv', index_col=0)
df_pivot_def

,index,C,H,O,S,N,P,Index,Calculated m/z,DBE,H/C,O/C,Heteroatom Class
Molecular Formula,,,,,,,,,,,,,
C6 H7 O2 S1 N2 P1,39,6.0,7.0,2.0,1.0,2.0,1.0,77,200.989309,5.0,1.166667,0.333333,N2 S1 P1 O2
C10 H18 O4,40,10.0,18.0,4.0,NaN,NaN,NaN,78,201.113233,2.0,1.800000,0.400000,O4
C10 H20 O4,41,10.0,20.0,4.0,NaN,NaN,NaN,80,203.128883,1.0,2.000000,0.400000,O4
C14 H22 O1,42,14.0,22.0,1.0,NaN,NaN,NaN,81,205.159789,4.0,1.571429,0.071429,O1
C10 H8 O3 S1,43,10.0,8.0,3.0,1.0,NaN,NaN,83,207.012139,7.0,0.800000,0.300000,S1 O3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
C47 H46 O3 S2 N3 P1,3153142,47.0,46.0,3.0,2.0,3.0,1.0,10031,794.264545,27.0,0.978723,0.063830,N3 S2 P1 O3
C58 H54 O3 S2 N1 P1,3153198,58.0,54.0,3.0,2.0,1.0,1.0,10066,906.320997,33.0,0.931034,0.051724,N1 S2 P1 O3
C51 H53 O1 S1 P1,3153270,51.0,53.0,1.0,1.0,NaN,1.0,86,743.348198,26.0,1.039216,0.019608,S1 P1 O1
C55 H37 O17 N1,3153272,55.0,37.0,17.0,NaN,1.0,NaN,88,982.198872,38.0,0.672727,0.309091,N1 O17
C37 H50 O22 S2 N3 P1,3153273,37.0,50.0,22.0,2.0,3.0,1.0,88,982.199223,15.0,1.351351,0.594595,N3 S2 P1 O22

In [5]:
df_sites_qc_T = df_sites_qc.T
df_sites_qc_T.index

Index(['C10 H10 O10', 'C10 H10 O3 N2', 'C10 H10 O4 N2', 'C10 H10 O4 S1',
       'C10 H10 O4 S1 N2', 'C10 H10 O5 N2', 'C10 H10 O5 S1',
       'C10 H10 O5 S1 N2', 'C10 H10 O6 N2', 'C10 H10 O6 S1',
       ...
       'C9 H9 O10 P1', 'C9 H9 O4 S2 N1', 'C9 H9 O6 P1', 'C9 H9 O6 S1 N3',
       'C9 H9 O7 N3', 'C9 H9 O8 N3', 'C9 H9 O8 S1 N1', 'C9 H9 O9 N1',
       'C9 H9 O9 N3', 'C9 H9 O9 S1 N1'],
      dtype='object', length=61956)

In [6]:
df_pivot_def.loc[df_sites_qc_T.index,df_pivot_def.columns[1:]]

,C,H,O,S,N,P,Index,Calculated m/z,DBE,H/C,O/C,Heteroatom Class
C10 H10 O10,10.0,10.0,10.0,NaN,NaN,NaN,1946,289.020120,6.0,1.0,1.000000,O10
C10 H10 O3 N2,10.0,10.0,3.0,NaN,2.0,NaN,526,205.061866,7.0,1.0,0.300000,N2 O3
C10 H10 O4 N2,10.0,10.0,4.0,NaN,2.0,NaN,698,221.056780,7.0,1.0,0.400000,N2 O4
C10 H10 O4 S1,10.0,10.0,4.0,1.0,NaN,NaN,1504,225.022704,6.0,1.0,0.400000,S1 O4
C10 H10 O4 S1 N2,10.0,10.0,4.0,1.0,2.0,NaN,2562,253.028852,7.0,1.0,0.400000,N2 S1 O4
...,...,...,...,...,...,...,...,...,...,...,...,...
C9 H9 O8 N3,9.0,9.0,8.0,NaN,3.0,NaN,3265,286.031688,7.0,1.0,0.888889,N3 O8
C9 H9 O8 S1 N1,9.0,9.0,8.0,1.0,1.0,NaN,3864,289.997611,6.0,1.0,0.888889,N1 S1 O8
C9 H9 O9 N1,9.0,9.0,9.0,NaN,1.0,NaN,3505,274.020454,6.0,1.0,1.000000,N1 O9
C9 H9 O9 N3,9.0,9.0,9.0,NaN,3.0,NaN,5877,302.026602,7.0,1.0,1.000000,N3 O9
C9 H9 O9 S1 N1,9.0,9.0,9.0,1.0,1.0,NaN,4435,305.992526,6.0,1.0,1.000000,N1 S1 O9

In [8]:
pd.concat([df_pivot_def.loc[df_sites_qc_T.index,df_pivot_def.columns[1:]], df_sites_qc_T], axis=1).to_csv('1000_soils_61959x124_def_031424.csv')

In [3]:
## formularity style output
df_longform = pd.concat([df_longForm_06, df_longForm_11])
df_longform

,Index,m/z,Calibrated m/z,Calculated m/z,Peak Height,Peak Area,Resolving Power,S/N,Ion Charge,m/z Error (ppm),...,O,S,N,13C,P,18O,Filename,34S,17O,15N
39,77,200.989236,200.989219,200.989309,7.493194e+06,1399.027540,1.121553e+06,34.084133,-1,-0.447152,...,2.0,1.0,2.0,NaN,1.0,NaN,corems2_1000S_MeOH-Blank_run1_Fir_22Apr22_300S...,NaN,NaN,NaN
40,78,201.113246,201.113230,201.113233,5.250224e+06,965.370917,1.120862e+06,23.881583,-1,-0.012653,...,4.0,NaN,NaN,NaN,NaN,NaN,corems2_1000S_MeOH-Blank_run1_Fir_22Apr22_300S...,NaN,NaN,NaN
41,80,203.128884,203.128868,203.128883,2.668193e+06,579.591303,1.109740e+06,12.136752,-1,-0.071483,...,4.0,NaN,NaN,NaN,NaN,NaN,corems2_1000S_MeOH-Blank_run1_Fir_22Apr22_300S...,NaN,NaN,NaN
42,81,205.159803,205.159788,205.159789,1.925085e+07,3614.401758,1.098754e+06,87.565939,-1,-0.006262,...,1.0,NaN,NaN,NaN,NaN,NaN,corems2_1000S_MeOH-Blank_run1_Fir_22Apr22_300S...,NaN,NaN,NaN
43,83,207.012146,207.012131,207.012139,2.607331e+06,460.232945,1.088922e+06,11.859913,-1,-0.038727,...,3.0,1.0,NaN,NaN,NaN,NaN,corems2_1000S_MeOH-Blank_run1_Fir_22Apr22_300S...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3153269,85,711.306586,711.306976,711.306727,4.214977e+06,10407.083656,2.535454e+05,19.926005,-1,0.350448,...,3.0,1.0,NaN,NaN,1.0,NaN,corems2_1000s_Lab_Blank_10_02Nov22_Mag_300SA_p...,NaN,NaN,NaN
3153270,86,743.347997,743.348402,743.348198,2.155465e+06,7152.694724,2.425776e+05,10.189805,-1,0.274247,...,1.0,1.0,NaN,NaN,1.0,NaN,corems2_1000s_Lab_Blank_10_02Nov22_Mag_300SA_p...,NaN,NaN,NaN
3153271,87,976.117266,976.117775,976.118256,3.172033e+06,14050.289930,2.309329e+05,14.995561,-1,-0.492698,...,20.0,2.0,3.0,NaN,NaN,NaN,corems2_1000s_Lab_Blank_10_02Nov22_Mag_300SA_p...,NaN,NaN,NaN
3153272,88,982.198260,982.198772,982.198872,2.243585e+06,12496.007821,1.835872e+05,10.606387,-1,-0.102566,...,17.0,NaN,1.0,NaN,NaN,NaN,corems2_1000s_Lab_Blank_10_02Nov22_Mag_300SA_p...,NaN,NaN,NaN
3153273,88,982.198260,982.198772,982.199223,2.243585e+06,12496.007821,1.835872e+05,10.606387,-1,-0.459798,...,22.0,2.0,3.0,NaN,1.0,NaN,corems2_1000s_Lab_Blank_10_02Nov22_Mag_300SA_p...,NaN,NaN,NaN

In [4]:
import numpy as np
Hmass = 1.007825
emass = 5.485e-4
deprotonatedmass = Hmass-emass

reportheaders = ['Mass','C','H','O','N','S','P','El_comp','Class','NeutralMass','Error_ppm','Candidates','H/C','O/C']

coremsheaders = ['Index', 'm/z', 'Calibrated m/z', 'Calculated m/z',
       'Peak Height', 'Peak Area', 'Resolving Power', 'S/N', 'Ion Charge',
       'm/z Error (ppm)', 'm/z Error Score', 'Isotopologue Similarity',
       'Confidence Score', 'DBE', 'H/C', 'O/C', 'Heteroatom Class', 'Ion Type',
       'Is Isotopologue', 'Mono Isotopic Index', 'Molecular Formula', 'C', 'H',
       'O', 'S', 'N', '13C', '34S', '18O', 'Filename', 'Sample', 'Order',
       '17O'],

def elcomp(dataseries):
    elcomps = []
    for i in range(len(dataseries)):
        elcomp = ''
        for x in ['C','H','O','N','S','P']:
            try:
                if dataseries.iloc[i][x]>0:
                    elcomp += x
            except:
                None
        elcomps.append(elcomp)
    return elcomps

def classcalc(dataseries): #from https://github.com/PNNL-Comp-Mass-Spec/Formularity/blob/master/CIA/FormularityProgram.cs
    cmpclasses = []
    for i in range(len(dataseries)):
        HC = dataseries.iloc[i]['H/C']
        OC = dataseries.iloc[i]['O/C']
        if (HC>=1.5) & (HC<2.5) & (OC>=0) & (OC<0.3):
            cmpclass = 'lipid'
        elif (HC>=0.8) & (HC<1.5) & (OC>=0) & (OC<0.125):
            cmpclass = 'unsatHC'
        elif (HC>=0.2) & (HC<0.8) & (OC>=0) & (OC<0.95):
            cmpclass = 'condHC'
        elif (HC>=1.5) & (HC<2.3) & (OC>=0.3) & (OC<0.55):
            cmpclass = 'protein'    
        elif (HC>=1.5) & (HC<2.2) & (OC>=0.55) & (OC<0.7):
            cmpclass = 'aminosugar'    
        elif (HC>=1.5) & (HC<2.2) & (OC>=0.7) & (OC<1.05):
            cmpclass = 'carb'
        elif (HC>=0.8) & (HC<1.5) & (OC>=0.125) & (OC<0.65):
            cmpclass = 'lignin'
        elif (HC>=0.8) & (HC<1.5) & (OC>=0.65) & (OC<1.1):
            cmpclass = 'tanin'
        else:
            cmpclass = 'undefined'
        cmpclasses.append(cmpclass)  
    return cmpclasses

In [6]:
df_pivot = df_longform.pivot(index='Molecular Formula',columns='Filename',values='Peak Height')
columns = reportheaders+list(set(df_longform['Filename']))

df_mean = df_longform.groupby('Molecular Formula').mean()

df_mean = df_mean.sort_index()
df_mean['H/C'] = df_mean['H']/df_mean['C']
df_mean['O/C'] = df_mean['O']/df_mean['C']
df_pivot['H/C']  = df_mean['H/C'] 
df_pivot['O/C']  = df_mean['O/C'] 

df_pivot['Mass'] = df_mean['Calibrated m/z']
for x in ['C','H','O','N','S','P']:
    try:
        df_pivot[x]= df_mean[x]
    except KeyError:
        df_pivot[x]  = np.nan
df_pivot['Class'] = classcalc(df_mean)
df_pivot['El_comp'] = elcomp(df_mean)
df_pivot['NeutralMass'] = df_mean['Calibrated m/z']+deprotonatedmass
df_pivot['Error_ppm'] = df_mean['m/z Error (ppm)']
df_pivot['Candidates'] = 1

df_pivot = df_pivot[columns]
df_pivot = df_pivot.sort_values(by='Mass')
#df_pivot = df_pivot.drop_duplicates(subset='Mass',keep=False)
df_pivot

Filename,Mass,C,H,O,N,S,P,El_comp,Class,NeutralMass,...,corems2_1000s_WY15_FTMS_SPE_BTM_3_01Nov22_Mag_300SA_p025_204_1_7217.csv,corems2_1000S_PPRH_FTMS_SPE_BTM_2_run2_Fir_22Apr22_300SA_p01_74_1_3431.csv,corems2_1000S_MeOH-Blank_run1_Fir_22Apr22_300SA_p01_28_1_3385.csv,corems2_1000S_OCTU_FTMS_SPE_BTM_2_run1_Fir_22Apr22_300SA_p01_15_1_3372.csv,corems2_1000S_PPRH_FTMS_SPE_TOP_3_run1_Fir_25Apr22_300SA_p01_1_1_3524.csv,corems2_1000s_UT19_FTMS_SPE_TOP_1_25Oct22_Mag_300SA_p025_96_1_7009.csv,corems2_1000S_PRS1_FTMS_SPE_BTM_2_run1_Fir_22Apr22_300SA_p01_44_1_3401.csv,corems2_1000S_FTA3_RR_FTMS_SPE_TOP_1_run2_Fir_22Apr22_300SA_p01_119_1_3476.csv,corems2_1000s_KONZ_FTMS_SPE_BTM_2_01Nov22_Mag_300SA_p025_221_1_7234.csv,corems2_1000s_WY09_FTMS_SPE_BTM_1_01Nov22_Mag_300SA_p025_191_1_7204.csv
Molecular Formula,,,,,,,,,,,,,,,,,,,,,
C7 H7 O4 S1 N1,200.002312,7.0,7.0,4.0,1.0,1.0,NaN,CHONS,lignin,201.009588,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C7 H7 O6 N1,200.020059,7.0,7.0,6.0,1.0,NaN,NaN,CHON,tanin,201.027336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C11 H7 O3 N1,200.035323,11.0,7.0,3.0,1.0,NaN,NaN,CHON,condHC,201.042600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.236546e+06
C10 H7 O2 N3,200.046563,10.0,7.0,2.0,3.0,NaN,NaN,CHON,condHC,201.053840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C8 H11 O5 N1,200.056449,8.0,11.0,5.0,1.0,NaN,NaN,CHON,lignin,201.063725,...,2.203305e+06,NaN,NaN,4.069188e+06,NaN,NaN,NaN,5.398071e+06,NaN,5.884562e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C43 H53 O21 S2 P1,999.218864,43.0,53.0,21.0,NaN,2.0,1.0,CHOSP,lignin,1000.226140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C48 H57 O21 P1,999.305603,48.0,57.0,21.0,NaN,NaN,1.0,CHOP,lignin,1000.312880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C61 H49 O10 N2 P1,999.305603,61.0,49.0,10.0,2.0,NaN,1.0,CHONP,lignin,1000.312880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C59 H52 O13 S1,999.305603,59.0,52.0,13.0,NaN,1.0,NaN,CHOS,lignin,1000.312880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C62 H53 O5 S2 N2 P1,999.305603,62.0,53.0,5.0,2.0,2.0,1.0,CHONSP,unsatHC,1000.312880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
df_pivot.columns[0:14]

NameError: name 'df_pivot' is not defined

In [7]:
df_def_old = pd.read_csv('/home/shic892/corems/1000_soils_61959x124_def_031424.csv', index_col=0)
df_def_old

,C,H,O,S,N,P,Index,Calculated m/z,DBE,H/C,...,WY01_BTM,WY01_TOP,WY03_BTM,WY03_TOP,WY09_BTM,WY09_TOP,WY10_BTM,WY10_TOP,WY15_BTM,WY15_TOP
C10 H10 O10,10.0,10.0,10.0,NaN,NaN,NaN,1946,289.020120,6.0,1.0,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
C10 H10 O3 N2,10.0,10.0,3.0,NaN,2.0,NaN,526,205.061866,7.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
C10 H10 O4 N2,10.0,10.0,4.0,NaN,2.0,NaN,698,221.056780,7.0,1.0,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
C10 H10 O4 S1,10.0,10.0,4.0,1.0,NaN,NaN,1504,225.022704,6.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
C10 H10 O4 S1 N2,10.0,10.0,4.0,1.0,2.0,NaN,2562,253.028852,7.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C9 H9 O8 N3,9.0,9.0,8.0,NaN,3.0,NaN,3265,286.031688,7.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C9 H9 O8 S1 N1,9.0,9.0,8.0,1.0,1.0,NaN,3864,289.997611,6.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
C9 H9 O9 N1,9.0,9.0,9.0,NaN,1.0,NaN,3505,274.020454,6.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
C9 H9 O9 N3,9.0,9.0,9.0,NaN,3.0,NaN,5877,302.026602,7.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C9 H9 O9 S1 N1,9.0,9.0,9.0,1.0,1.0,NaN,4435,305.992526,6.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df_pivot.loc[df_def_old.index, df_pivot.columns[0:14]].to_csv('1000s_corems2_formularity_definition.csv')